#!/bin/bash -e

exec 2>&1

SCRIPTPATH=$( cd "$(dirname "$0")" ; pwd -P )
export HOME=$( cd "${SCRIPTPATH}/../../.." ; pwd -P )

MELPA_REPO="${SCRIPTPATH}/../.."
cd "${MELPA_REPO}"

DISK_DELAY=$((2 * 60))
echo `date +%Y-%m-%d-%H:%M.%S`

ECUKES_EMACS=${EMACS:-$(which emacs)}

echo "*** Emacs version ***"
echo "ECUKES_EMACS = $ECUKES_EMACS"
"$ECUKES_EMACS" --version
echo

# cask exec ecukes

"$ECUKES_EMACS" --batch --eval "(progn (load-file \"disk-status.el\")(ab/disk-status))"

echo "Disk info successful"

sleep $DISK_DELAY

